### ISSUE TITLE
Set is not allow some of expression. 

### ISSUE THREAD

**Issue by palamike** [RobinRadic/blade-extensions#19]
@set does not allow some of expression. 

Eg. 
@set('somevar',$object->getValue())
@set('somevar',$object->getValue('params')) 
@set('somevar',somefunctionCall('Params'))
@set('somevar',Session::get('Params')) 

Once I've use the expression above, It has nothing compiled in compiled template file and of cause it has no variable setting.

still not work around, please help to fix.

**Comment by RobinRadic** [comment]
just created a new test case for this issue and it seems it is caused by not having a space after the first parameter comma. 

Not working:
'''php
@set('somevar',somefunctionCall('Params'))
@set('somevar',$object->getValue('params'))
@set('somevar',$object->getValue())
'''

Working:
'''php
@set('somevar', somefunctionCall('Params'))
@set('somevar', $object->getValue('params'))
@set('somevar', $object->getValue())
'''

**Comment by palamike** [comment]
Hi, Thank You.
