### ISSUE TITLE
Markdown Issues

### ISSUE THREAD

**Issue by ziming** [RobinRadic/blade-extensions#24]
Hi, after installing this package

I started to have issues with @GrahamCampbell's Markdown package

https://github.com/GrahamCampbell/Laravel-Markdown

Upon further investigation it is due to the markdown features blade-extensions provide, hence I removed Laravel-Markdown and included "erusev/parsedown": "~1.5".

I change my blade template from

```
Markdown::convertToHtml(e($comment->body))

to

@markdown
{{$comment->body}}
@endmarkdown
```

However what I got instead was

```
<?php echo $comment->body; ?>
```

in my view. Would like to ask if I used the @markdown tag wrongly.

**Comment by RobinRadic** [comment]
That's because of how the blade views are 'compiled'.
```php
@markdown
# This will work
** because during compiling, the markdown text is already here **
@endmarkdown
```

That will be compiled to:
```php
<?php echo \Radic\BladeExtensions\Helpers\Markdown::parse(<<<'EOT'
 # This will work
** because during compiling, the markdown text is already here **
EOT
); ?>
```

While your example, will be compiled to
```php
<?php echo \Radic\BladeExtensions\Helpers\Markdown::parse(<<<'EOT'
<?php echo $comment->body; ?>
EOT
); ?>
```

Which is not working as `{{$comment->body}}` gets replaced with `<?php echo $comment->body; ?>` inside a HEREDOC string.

Now, there's several options which you can try:

1. You can use the 'Markdown' Facade that is included in `Radic\BladeExtensions\Facades\Markdown`. Then you could use `{{ Markdown::render($comment->body) }}`.
2. You can use the same way as the directive but directly like `{{  \Radic\BladeExtensions\Helpers\Markdown::parse($comment->body) }}`
3. You can use the markdown binding, which is the same as the facade `{{ app('markdown')->render($comment->body) }}`

Alternatively, if your aim was to use Graham Campbell's markdown package and blade-extensions got it the way of that then open up your `blade_extensions.php` config file and disable blade-extension's markdown support entirely:
```php
return array(
    // ...
    'markdown' => array(
        'enabled' => true, // set to false
        // ...
    )
);
```

These options should be sufficient to deal with the problem your having. If not, let me know.

**Comment by younes0** [comment]
the simplest way is simply to remove graham's markdown package 

by the way, why not include "erusev/parsedown": "~1.5" by default ?

**Comment by RobinRadic** [comment]
I'd like to keep it optional as its a very specific feature that probably 80-90% of the projects isn't even used. Besides that, blade-extensions provides a way to use a custom markdown renderer/compiler. By default it ships with both `erusev/parsedown` aswell as `kzykhyz/ciconia` support. Including either package by default would in my opinion be illogical and contradicting.

**Comment by younes0** [comment]
Very clear, well that's a very useful feature to me ;)

**Comment by brandonferens** [comment]
Even with markdown disabled, I was getting the issue thrown that Parsedown didn't exist and had to pull in "erusev/parsedown". Just thought I'd let you know.
