### ISSUE TITLE
@foreach()   runs multiple queries

### ISSUE THREAD

**Issue by whipsterCZ** [RobinRadic/blade-extensions#36]
Hi again.

I found another bug in BladeExtensions.

~~~
@foreach(App\Office::all() as $office)
@endforeach
~~~

runs 2 queries
~~~
select * from `offices` 
select * from `offices` 
~~~

If I disable **Radic\BladeExtensions\BladeExtensionsServiceProvider**
it runs just one unique query.

Can you explain this behaviour? Thanks

**Comment by RobinRadic** [comment]
Ah yeah, i've already encountered this myself and will include this soon in a fix.

The problem is quite simple:
```php
@foreach(App\Office::all() as $office)
```
is replaced by
```php
app('blade.helpers')->get('loop')->newLoop(App\Office::all());
foreach(App\Office::all() as $office):
    $loop = app('blade.helpers')->get('loop')->loop();
```

You have 2 options:
1: use `@set('offices', App\Office::all())` then `@foreach($offices as $office)`
2: Add a overide. edit the `blade_extensions.php` config file:
```php
return array(
    'overrides' => [
        'foreach'   => [
            'pattern'     => '/(?<!\\w)(\\s*)@foreach(?:\\s*)\\((.*)(?:\\sas)(.*)\\)/',
            'replacement' => <<<'EOT'
$1<?php
app('blade.helpers')->get('loop')->newLoop($_loop_data = $2);
foreach($_loop_data as $3):
    $loop = app('blade.helpers')->get('loop')->loop();
?>
EOT
        ]
    ]
);
```

Option 2 will probably give errors if you have a child foreach eg:
```php
@foreach($data as $d)
     @foreach($d['names'] as $name)
```

So until i properly fix this in a new release, you'd probably want to use option 1.

**Comment by whipsterCZ** [comment]
Variant with @set('office',App\Office:all()) produce same output..
as far as i remember..

Thanks for your attention..

**Comment by RobinRadic** [comment]
`6.1.0` tagged. fixes this
