### ISSUE TITLE
Call to a member function newLoop() on null

### ISSUE THREAD

**Issue by challet** [RobinRadic/blade-extensions#67]
Hi,

Using Laravel 5.2, it looks like the [_compileExtensions_ method](https://github.com/laravel/framework/blob/5.2/src/Illuminate/View/Compilers/BladeCompiler.php#L236) is only called when the view is firstly compiled, and [not on the opposite case](https://github.com/laravel/framework/blob/5.2/src/Illuminate/View/Engines/CompilerEngine.php#L50).

Though, in the later case the view display still try to find an `app('blade-extensions.helpers')->get('loop')` when reaching a **@foreach** directive.
Which finds itself being NULL, because the [hook callbacks](https://github.com/RobinRadic/blade-extensions/blob/master/src/DirectiveRegistry.php#L96) are never called (through the _compileExtensions_ pointed before).

Is there any other way to register the extensions, no matter the view is compiled or not ?

**Comment by RobinRadic** [comment]
Could you provide 'complete' code so i can test around?

I think you want to do something with the hooker

```php
App::booting(function($app){
   $registry = app('blade-extensions.directives');
  $registry->setHooker(function(){

                $registry->getCompiler()->extend(function ($value) use ($name) {
            foreach ($registry->getNames() as $name) {
                    return $registry->call($name, [$value]);
            }
                });
  });

});


```


Or you could overide the registry's ioc binding with your extended class and have more control:
```php
namepsace App;

class MyDirectiveRegistry extends  Radic\BladeExtensions\DirectiveRegistry {
    public function hookToCompiler()
    {
        if (true === $this->hooked) {
            return;
        }
        $this->hooked = true;

        if (null === $this->hooker) {
            foreach ($this->getNames() as $name) {
                $this->getCompiler()->extend(function ($value) use ($name) {
                    return $this->call($name, [$value]);
                });
            }
        } else {
            $this->app->call($this->hooker, [], 'handle');
        }
    }

}
```

**Comment by Levivb** [comment]
FYI: the above solutions doesn't work.<br>
I've been pulling my hair out over this exception for much longer than what would reasonable be expected from upgrading third party packages.<br>
The problem is easily reproducible in a clean Laravel 5.5 installation when calling the `@minify('html')` directive and than a `@foreach`<br>
Until a proper fix is implemented from the package, I'll have to other choice but to assume build 7.0 is broken.  I'll leave it at version 6.2, even though that one has the rather nasty bug of multiple assignment in the `@set` directive (https://github.com/RobinRadic/blade-extensions/issues/68)
